# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50d21e2df0563045f2bb287b941af6075d9d47bf93a01ad94898a408e626c5f1f7a6e90e49e1bd04c0c13269c3a25b1868de2dabcc2abd64a2c3cf906a83fe0a

test:
  secret_key_base: c0767c56794c579ab6461b51d4943968a70da9d4f931954ba6b07885afd3263c9544f9524028219004df57b2370c13ba170f841f4f0fadff805a37404367beb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
